# Generated by Django 3.1.5 on 2021-01-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210124_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newflatpage',
            old_name='description',
            new_name='content',
        ),
    ]
