# Generated by Django 3.1.5 on 2021-01-24 21:15

from django.db import migrations


def stock_availability(apps, schema_editor):

    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.in_stock = 1
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_product_seller_tag'),
    ]

    operations = [
        migrations.RunPython(stock_availability),
    ]
