# Generated by Django 3.1.5 on 2021-01-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210125_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stok',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='Наличие'),
            preserve_default=False,
        ),
    ]
