# Generated by Django 3.1.5 on 2021-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
